export interface CityEntry {
  city: string;
  canton: string;
  country: string;
  flag: string;
}

// Currently Switzerland only — more countries coming soon!
export const cityDatabase: CityEntry[] = [
  // Major cities
  { city: "Zurich", canton: "ZH", country: "Switzerland", flag: "🇨🇭" },
  { city: "Geneva", canton: "GE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Basel", canton: "BS", country: "Switzerland", flag: "🇨🇭" },
  { city: "Bern", canton: "BE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Lausanne", canton: "VD", country: "Switzerland", flag: "🇨🇭" },
  { city: "Lucerne", canton: "LU", country: "Switzerland", flag: "🇨🇭" },
  { city: "Winterthur", canton: "ZH", country: "Switzerland", flag: "🇨🇭" },
  { city: "St. Gallen", canton: "SG", country: "Switzerland", flag: "🇨🇭" },
  { city: "Lugano", canton: "TI", country: "Switzerland", flag: "🇨🇭" },
  { city: "Zug", canton: "ZG", country: "Switzerland", flag: "🇨🇭" },

  // Additional main cities
  { city: "Biel/Bienne", canton: "BE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Thun", canton: "BE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Köniz", canton: "BE", country: "Switzerland", flag: "🇨🇭" },
  { city: "La Chaux-de-Fonds", canton: "NE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Fribourg", canton: "FR", country: "Switzerland", flag: "🇨🇭" },
  { city: "Schaffhausen", canton: "SH", country: "Switzerland", flag: "🇨🇭" },
  { city: "Chur", canton: "GR", country: "Switzerland", flag: "🇨🇭" },
  { city: "Neuchâtel", canton: "NE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Sion", canton: "VS", country: "Switzerland", flag: "🇨🇭" },
  { city: "Uster", canton: "ZH", country: "Switzerland", flag: "🇨🇭" },
  { city: "Emmen", canton: "LU", country: "Switzerland", flag: "🇨🇭" },
  { city: "Kriens", canton: "LU", country: "Switzerland", flag: "🇨🇭" },
  { city: "Rapperswil-Jona", canton: "SG", country: "Switzerland", flag: "🇨🇭" },
  { city: "Yverdon-les-Bains", canton: "VD", country: "Switzerland", flag: "🇨🇭" },
  { city: "Dübendorf", canton: "ZH", country: "Switzerland", flag: "🇨🇭" },
  { city: "Dietikon", canton: "ZH", country: "Switzerland", flag: "🇨🇭" },
  { city: "Montreux", canton: "VD", country: "Switzerland", flag: "🇨🇭" },
  { city: "Frauenfeld", canton: "TG", country: "Switzerland", flag: "🇨🇭" },
  { city: "Wetzikon", canton: "ZH", country: "Switzerland", flag: "🇨🇭" },
  { city: "Aarau", canton: "AG", country: "Switzerland", flag: "🇨🇭" },
  { city: "Baden", canton: "AG", country: "Switzerland", flag: "🇨🇭" },
  { city: "Wil", canton: "SG", country: "Switzerland", flag: "🇨🇭" },
  { city: "Olten", canton: "SO", country: "Switzerland", flag: "🇨🇭" },
  { city: "Solothurn", canton: "SO", country: "Switzerland", flag: "🇨🇭" },
  { city: "Bellinzona", canton: "TI", country: "Switzerland", flag: "🇨🇭" },
  { city: "Locarno", canton: "TI", country: "Switzerland", flag: "🇨🇭" },
  { city: "Nyon", canton: "VD", country: "Switzerland", flag: "🇨🇭" },
  { city: "Morges", canton: "VD", country: "Switzerland", flag: "🇨🇭" },
  { city: "Vevey", canton: "VD", country: "Switzerland", flag: "🇨🇭" },
  { city: "Bülach", canton: "ZH", country: "Switzerland", flag: "🇨🇭" },
  { city: "Horgen", canton: "ZH", country: "Switzerland", flag: "🇨🇭" },
  { city: "Wädenswil", canton: "ZH", country: "Switzerland", flag: "🇨🇭" },
  { city: "Kloten", canton: "ZH", country: "Switzerland", flag: "🇨🇭" },
  { city: "Renens", canton: "VD", country: "Switzerland", flag: "🇨🇭" },
  { city: "Carouge", canton: "GE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Vernier", canton: "GE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Lancy", canton: "GE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Meyrin", canton: "GE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Davos", canton: "GR", country: "Switzerland", flag: "🇨🇭" },
  { city: "Interlaken", canton: "BE", country: "Switzerland", flag: "🇨🇭" },
  { city: "Zermatt", canton: "VS", country: "Switzerland", flag: "🇨🇭" },
  { city: "Martigny", canton: "VS", country: "Switzerland", flag: "🇨🇭" },
  { city: "Delémont", canton: "JU", country: "Switzerland", flag: "🇨🇭" },
  { city: "Herisau", canton: "AR", country: "Switzerland", flag: "🇨🇭" },
  { city: "Appenzell", canton: "AI", country: "Switzerland", flag: "🇨🇭" },
  { city: "Sarnen", canton: "OW", country: "Switzerland", flag: "🇨🇭" },
  { city: "Stans", canton: "NW", country: "Switzerland", flag: "🇨🇭" },
  { city: "Schwyz", canton: "SZ", country: "Switzerland", flag: "🇨🇭" },
  { city: "Altdorf", canton: "UR", country: "Switzerland", flag: "🇨🇭" },
  { city: "Glarus", canton: "GL", country: "Switzerland", flag: "🇨🇭" },
  { city: "Liestal", canton: "BL", country: "Switzerland", flag: "🇨🇭" },
];
